package net.ayataka.kordis.rest

import io.ktor.http.HttpMethod

const val BASE = "https://discordapp.com/api/v6"

sealed class Endpoint(val method: HttpMethod, path: String) {
    val url = BASE + path

    data class GET_GUILD_AUDIT_LOG(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/audit-logs")
    data class GET_CHANNEL(val channel_id: Long): Endpoint(HttpMethod.Get, "/channels/$channel_id")
    data class MODIFY_CHANNEL_PUT(val channel_id: Long): Endpoint(HttpMethod.Put, "/channels/$channel_id")
    data class MODIFY_CHANNEL_PATCH(val channel_id: Long): Endpoint(HttpMethod.Patch, "/channels/$channel_id")
    data class DELETE_CHANNEL(val channel_id: Long): Endpoint(HttpMethod.Delete, "/channels/$channel_id")
    data class EDIT_CHANNEL_PERMISSIONS(val channel_id: Long, val overwrite_id: Long): Endpoint(HttpMethod.Put, "/channels/$channel_id/permissions/$overwrite_id")
    data class DELETE_CHANNEL_PERMISSION(val channel_id: Long, val overwrite_id: Long): Endpoint(HttpMethod.Delete, "/channels/$channel_id/permissions/$overwrite_id")
    data class GET_CHANNEL_INVITES(val channel_id: Long): Endpoint(HttpMethod.Get, "/channels/$channel_id/invites")
    data class CREATE_CHANNEL_INVITE(val channel_id: Long): Endpoint(HttpMethod.Post, "/channels/$channel_id/invites")
    data class GET_CHANNEL_MESSAGE(val channel_id: Long, val message_id: Long): Endpoint(HttpMethod.Get, "/channels/$channel_id/messages/$message_id")
    data class GET_CHANNEL_MESSAGES(val channel_id: Long): Endpoint(HttpMethod.Get, "/channels/$channel_id/messages")
    data class CREATE_MESSAGE(val channel_id: Long): Endpoint(HttpMethod.Post, "/channels/$channel_id/messages")
    data class EDIT_MESSAGE(val channel_id: Long, val message_id: Long): Endpoint(HttpMethod.Patch, "/channels/$channel_id/messages/$message_id")
    data class DELETE_MESSAGE(val channel_id: Long, val message_id: Long): Endpoint(HttpMethod.Delete, "/channels/$channel_id/messages/$message_id")
    data class BULK_DELETE_MESSAGES(val channel_id: Long): Endpoint(HttpMethod.Post, "/channels/$channel_id/messages/bulk-delete")
    data class GET_REACTIONS(val channel_id: Long, val message_id: Long, val emoji: String): Endpoint(HttpMethod.Get, "/channels/$channel_id/messages/$message_id/reactions/$emoji")
    data class CREATE_REACTION(val channel_id: Long, val message_id: Long, val emoji: String): Endpoint(HttpMethod.Put, "/channels/$channel_id/messages/$message_id/reactions/$emoji/@me")
    data class DELETE_OWN_REACTION(val channel_id: Long, val message_id: Long, val emoji: String): Endpoint(HttpMethod.Delete, "/channels/$channel_id/messages/$message_id/reactions/$emoji/@me")
    data class DELETE_USER_REACTION(val channel_id: Long, val message_id: Long, val emoji: String, val user_id: Long): Endpoint(HttpMethod.Delete, "/channels/$channel_id/messages/$message_id/reactions/$emoji/$user_id")
    data class DELETE_ALL_REACTIONS(val channel_id: Long, val message_id: Long): Endpoint(HttpMethod.Delete, "/channels/$channel_id/messages/$message_id/reactions")
    data class GET_PINNED_MESSAGES(val channel_id: Long): Endpoint(HttpMethod.Get, "/channels/$channel_id/pins")
    data class ADD_PINNED_CHANNEL_MESSAGE(val channel_id: Long, val message_id: Long): Endpoint(HttpMethod.Put, "/channels/$channel_id/pins/$message_id")
    data class DELETE_PINNED_CHANNEL_MESSAGE(val channel_id: Long, val message_id: Long): Endpoint(HttpMethod.Delete, "/channels/$channel_id/pins/$message_id")
    data class LIST_GUILD_EMOJIS(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/emojis")
    data class GET_GUILD_EMOJI(val guild_id: Long, val emoji_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/emojis/$emoji_id")
    data class CREATE_GUILD_EMOJI(val guild_id: Long): Endpoint(HttpMethod.Post, "/guilds/$guild_id/emojis")
    data class MODIFY_GUILD_EMOJI(val guild_id: Long, val emoji_id: Long): Endpoint(HttpMethod.Patch, "/guilds/$guild_id/emojis/$emoji_id")
    data class DELETE_GUILD_EMOJI(val guild_id: Long, val emoji_id: Long): Endpoint(HttpMethod.Delete, "/guilds/$guild_id/emojis/$emoji_id")
    object CREATE_GUILD: Endpoint(HttpMethod.Post, "/guilds")
    data class GET_GUILD(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id")
    data class MODIFY_GUILD(val guild_id: Long): Endpoint(HttpMethod.Patch, "/guilds/$guild_id")
    data class DELETE_GUILD(val guild_id: Long): Endpoint(HttpMethod.Delete, "/guilds/$guild_id")
    data class GET_GUILD_CHANNELS(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/channels")
    data class CREATE_GUILD_CHANNEL(val guild_id: Long): Endpoint(HttpMethod.Post, "/guilds/$guild_id/channels")
    data class MODIFY_GUILD_CHANNEL_POSITIONS(val guild_id: Long): Endpoint(HttpMethod.Patch, "/guilds/$guild_id/channels")
    data class GET_GUILD_MEMBER(val guild_id: Long, val user_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/members/$user_id")
    data class LIST_GUILD_MEMBERS(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/members")
    data class ADD_GUILD_MEMBER(val guild_id: Long, val user_id: Long): Endpoint(HttpMethod.Put, "/guilds/$guild_id/members/$user_id")
    data class MODIFY_GUILD_MEMBER(val guild_id: Long, val user_id: Long): Endpoint(HttpMethod.Patch, "/guilds/$guild_id/members/$user_id")
    data class MODIFY_CURRENT_USER_NICK(val guild_id: Long): Endpoint(HttpMethod.Patch, "/guilds/$guild_id/members/@me/nick")
    data class ADD_GUILD_MEMBER_ROLE(val guild_id: Long, val user_id: Long, val role_id: Long): Endpoint(HttpMethod.Put, "/guilds/$guild_id/members/$user_id/roles/$role_id")
    data class REMOVE_GUILD_MEMBER_ROLE(val guild_id: Long, val user_id: Long, val role_id: Long): Endpoint(HttpMethod.Delete, "/guilds/$guild_id/members/$user_id/roles/$role_id")
    data class REMOVE_GUILD_MEMBER(val guild_id: Long, val user_id: Long): Endpoint(HttpMethod.Delete, "/guilds/$guild_id/members/$user_id")
    data class GET_GUILD_BANS(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/bans")
    data class GET_GUILD_BAN(val guild_id: Long, val user_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/bans/$user_id")
    data class CREATE_GUILD_BAN(val guild_id: Long, val user_id: Long): Endpoint(HttpMethod.Put, "/guilds/$guild_id/bans/$user_id")
    data class REMOVE_GUILD_BAN(val guild_id: Long, val user_id: Long): Endpoint(HttpMethod.Delete, "/guilds/$guild_id/bans/$user_id")
    data class GET_GUILD_ROLES(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/roles")
    data class CREATE_GUILD_ROLE(val guild_id: Long): Endpoint(HttpMethod.Post, "/guilds/$guild_id/roles")
    data class MODIFY_GUILD_ROLE_POSITIONS(val guild_id: Long): Endpoint(HttpMethod.Patch, "/guilds/$guild_id/roles")
    data class MODIFY_GUILD_ROLE(val guild_id: Long, val role_id: Long): Endpoint(HttpMethod.Patch, "/guilds/$guild_id/roles/$role_id")
    data class DELETE_GUILD_ROLE(val guild_id: Long, val role_id: Long): Endpoint(HttpMethod.Delete, "/guilds/$guild_id/roles/$role_id")
    data class GET_GUILD_PRUNE_COUNT(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/prune")
    data class BEGIN_GUILD_PRUNE(val guild_id: Long): Endpoint(HttpMethod.Post, "/guilds/$guild_id/prune")
    data class GET_GUILD_VOICE_REGIONS(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/regions")
    data class GET_GUILD_INVITES(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/invites")
    data class GET_GUILD_VANITY_URL(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/vanity-url")
    data class GET_INVITE(val invite_code: String): Endpoint(HttpMethod.Get, "/invites/$invite_code")
    data class DELETE_INVITE(val invite_code: String): Endpoint(HttpMethod.Delete, "/invites/$invite_code")
    object GET_CURRENT_USER: Endpoint(HttpMethod.Get, "/users/@me")
    data class GET_USER(val user_id: Long): Endpoint(HttpMethod.Get, "/users/$user_id")
    object MODIFY_CURRENT_USER: Endpoint(HttpMethod.Patch, "/users/@me")
    object GET_CURRENT_USER_GUILDS: Endpoint(HttpMethod.Get, "/users/@me/guilds")
    data class LEAVE_GUILD(val guild_id: Long): Endpoint(HttpMethod.Delete, "/users/@me/guilds/$guild_id")
    object GET_USER_DMS: Endpoint(HttpMethod.Get, "/users/@me/channels")
    object CREATE_DM: Endpoint(HttpMethod.Post, "/users/@me/channels")
    object CREATE_GROUP_DM: Endpoint(HttpMethod.Post, "/users/@me/channels")
    object GET_USER_CONNECTIONS: Endpoint(HttpMethod.Get, "/users/@me/connections")
    object LIST_VOICE_REGIONS: Endpoint(HttpMethod.Get, "/voice/regions")
    data class CREATE_WEBHOOK(val channel_id: Long): Endpoint(HttpMethod.Post, "/channels/$channel_id/webhooks")
    data class GET_CHANNEL_WEBHOOKS(val channel_id: Long): Endpoint(HttpMethod.Get, "/channels/$channel_id/webhooks")
    data class GET_GUILD_WEBHOOKS(val guild_id: Long): Endpoint(HttpMethod.Get, "/guilds/$guild_id/webhooks")
    data class GET_WEBHOOK(val webhook_id: Long): Endpoint(HttpMethod.Get, "/webhooks/$webhook_id")
    data class GET_WEBHOOK_WITH_TOKEN(val webhook_id: Long, val webhook_token: String): Endpoint(HttpMethod.Get, " /webhooks/$webhook_id/$webhook_token")
    data class MODIFY_WEBHOOK(val webhook_id: Long): Endpoint(HttpMethod.Patch, "/webhooks/$webhook_id")
    data class MODIFY_WEBHOOK_WITH_TOKEN(val webhook_id: Long, val webhook_token: String): Endpoint(HttpMethod.Patch, "/webhooks/$webhook_id/$webhook_token")
    data class DELETE_WEBHOOK(val webhook_id: Long): Endpoint(HttpMethod.Delete, "/webhooks/$webhook_id")
    data class DELETE_WEBHOOK_WITH_TOKEN(val webhook_id: Long, val webhook_token: String): Endpoint(HttpMethod.Delete, "/webhooks/$webhook_id/$webhook_token")
    data class EXECUTE_WEBHOOK(val webhook_id: Long, val webhook_token: String): Endpoint(HttpMethod.Post, "/webhooks/$webhook_id/$webhook_token")
    data class EXECUTE_SLACK_WEBHOOK(val webhook_id: Long, val webhook_token: String): Endpoint(HttpMethod.Post, "/webhooks/$webhook_id/$webhook_token/slack")
    data class EXECUTE_GITHUB_WEBHOOK(val webhook_id: Long, val webhook_token: String): Endpoint(HttpMethod.Post, "/webhooks/$webhook_id/$webhook_token/github")
    object GET_GATEWAY: Endpoint(HttpMethod.Get, "/gateway")
    object GET_GATEWAY_BOT: Endpoint(HttpMethod.Get, "/gateway/bot")
}